'use strict';
const $=id=>document.getElementById(id);
const state={libraries:{},indexes:{},rows:[],results:[],running:false};
const HEADER_ALIASES={id:['样本id','样本编号','编号','商品编号','物料编码','id'],title:['商品标题','商品名称','标题','应标未标商品名称','name']};
const GENERIC_MARKERS=['清洗剂','清洗液','复合剂','添加剂','助剂','处理剂','改性剂','促进剂','催化剂','润滑油','机油','液压油','齿轮油','切削液','防冻液','涂料','油漆','胶黏剂','粘合剂','树脂','母粒','制剂','农药','肥料','溶剂','稀释剂','工业助剂'];
const MIXTURE_MARKERS=['混合物','混合','复合','残液','废液','废料','废品','危废','副产品','副产','回收料','回收液','焦油','粗品','粗芳烃','裂解','落地料','浆液'];
const CONTEXT_MARKERS=[...new Set(['发动机专用油','发动机润滑油','发动机油','柴油机','汽油机','燃气发动机','发动机','机油','润滑油','复合剂','清净剂','添加剂','抗磨剂','抗氧剂','防锈剂','缓蚀剂','稳定剂','催化剂','助剂','母粒','色母粒','树脂','橡胶','共聚物','聚合物','低聚物','涂料','胶黏剂','清洗液','清洗剂','专用油','压缩机油','齿轮油','液压油','防冻液','处理剂','改性剂','促进剂','设备','装置','阀门','管道','检测仪','标准气','校准气','标气','原料药','制剂','农药','肥料','复合肥','试剂盒','调和用','调和剂'])].sort((a,b)=>b.length-a.length);
const CHEM_CHARS=new Set(Array.from('一二三四五六七八九十邻间对正异叔仲新次高过亚偏重焦连原单双多钠钾铵钙镁铝锌铁铜钡锂银汞铅锰镍钴锡硼硅钛钒铬钼钨锆锶铍铯铷盐酯醚胺酰酐醇酚酮醛腈烷烯炔苯磷硫氯溴碘氟氧氢硝亚基化聚酸根体物液羟羧碳'));
const PRIOR_MARKERS=['树脂','橡胶','共聚物','聚合物','低聚物','润滑油','机油','复合剂','添加剂','助剂','母粒','清洗剂','涂料','装置','设备'];
const STATUS={candidate:'标题命中候选（待核验）',info:'信息不足',none:'未形成候选',error:'数据错误'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function normTerm(v){return String(v??'').normalize('NFKC').toLowerCase().replace(/[\s\u3000，,；;：:。·•_—–－\-\/\\|\[\]【】()（）]/g,'');}
function searchText(v){let s=String(v??'').normalize('NFKC').toLowerCase();s=s.replace(/\b\d{2,7}-\d{2}-\d\b/g,'');s=s.replace(/[\[【(（\]】)）\s\u3000；;。\/\\|]+/g,'|');s=s.replace(/[，,：:·•_—–－\-]/g,'');return s.replace(/\|+/g,'|');}
function cleanTitleCore(v){let s=searchText(v);['工业级','试剂级','分析纯','化学纯','优级纯','食品级','医药级','电子级','高纯','纯品','国产','进口','现货','桶装','瓶装','袋装','槽车装','吨桶','散水','液体','固体','粉末','颗粒','片状','晶体','水溶液','溶液','含量','浓度','纯度','优等品','一等品','合格品','协议品'].forEach(x=>{s=s.split(x).join('')});return s.replace(/\|/g,'');}
function validCas(cas){if(!/^\d{2,7}-\d{2}-\d$/.test(cas))return false;const d=cas.replace(/-/g,'');let sum=0;for(let i=d.length-2,w=1;i>=0;i--,w++)sum+=Number(d[i])*w;return sum%10===Number(d.at(-1));}
function extractCas(v){return (String(v??'').match(/\b\d{2,7}-\d{2}-\d\b/g)||[]).find(validCas)||'';}
function ruleTerms(r){return [r.name,...(r.aliases||[]),...(r.match_terms||[]),...(r.family_prefixes||[])].filter(Boolean);}
function addMap(map,key,val){if(!key)return;const a=map.get(key)||[];a.push(val);map.set(key,a);}
function buildIndex(lib){const buckets=new Map(),cas=new Map(),one=[];for(const rule of lib.rules||[]){if(rule.active===false)continue;for(const c of rule.cas||[])addMap(cas,c,rule);const seen=new Set();for(const raw of ruleTerms(rule)){const term=normTerm(raw);if(!term||seen.has(term))continue;seen.add(term);const item={rule,raw,term};if(term.length===1)one.push(item);else addMap(buckets,term.slice(0,2),item);}}for(const a of buckets.values())a.sort((x,y)=>y.term.length-x.term.length);return {buckets,cas,one};}
function contextReason(text,term,start,end){const before=text.slice(0,start),after=text.slice(end),near=before.slice(-12);if(['不含','非','去除','脱除'].some(p=>near.endsWith(p)))return '否定或去除语义';const grade=/^(合格品|协议品|优等品|一等品|一级|二级|废品|劣质品|过渡料|散装|\d)/.test(after.replace(/^\|/,''));if(grade&&PRIOR_MARKERS.some(m=>before.includes(m)))return '位于另一制品名称之后';const ws=Math.max(0,start-14),we=Math.min(text.length,end+28);for(const marker of CONTEXT_MARKERS){let pos=text.indexOf(marker,ws);while(pos>=0&&pos<we){const me=pos+marker.length,overlap=pos<end&&me>start,inside=pos>=start&&me<=end&&term.includes(marker),follows=pos>=end&&pos-end<=14;if((overlap&&!inside)||follows)return `邻近用途或制品词“${marker}”`;pos=text.indexOf(marker,pos+1);}}const next=after.replace(/^\|/,'')[0],prev=before.replace(/\|$/,'').at(-1);if(after&&!after.startsWith('|')&&next&&CHEM_CHARS.has(next))return `后接“${next}”，可能是另一化合物的一部分`;if(before&&!before.endsWith('|')&&prev&&CHEM_CHARS.has(prev))return `前接“${prev}”，可能是另一化合物的一部分`;return '';}
function matchLibrary(category,title){const idx=state.indexes[category],text=searchText(title),casNo=extractCas(title),found=new Map();const add=(rule,raw,term,quality)=>{const key=rule.id||`${rule.catalog_no}|${rule.name}`;const old=found.get(key);if(!old||term.length>old.term.length)found.set(key,{rule,raw,term,quality});};if(casNo)for(const r of idx.cas.get(casNo)||[])add(r,casNo,casNo,'cas');const entries=new Map();for(let i=0;i<text.length-1;i++)for(const x of idx.buckets.get(text.slice(i,i+2))||[])entries.set(`${x.rule.id}|${x.term}`,x);for(const x of entries.values()){let pos=text.indexOf(x.term);while(pos>=0){if(!contextReason(text,x.term,pos,pos+x.term.length)){add(x.rule,x.raw,x.term,'title');break}pos=text.indexOf(x.term,pos+1);}}const core=cleanTitleCore(title);for(const x of idx.one)if(core===x.term)add(x.rule,x.raw,x.term,'exact-short');return [...found.values()].sort((a,b)=>b.term.length-a.term.length).slice(0,12);}
function names(matches){return [...new Set(matches.map(x=>x.raw||x.rule.name))];}
function hasConditional(matches){return matches.some(x=>(x.rule.conditions||[]).length||(x.rule.condition_groups||[]).length||x.rule.conditional_complex||x.rule.special_rule||String(x.rule.catalog_no)==='2828');}
function analyze(row){const id=String(row.id??'').trim(),title=String(row.title??'').trim();if(!title)return {id,title,category:'数据错误',toxic:STATUS.error,hazard:STATUS.error,explosive:STATUS.error,candidates:'',action:'修正数据',note:'商品标题为空。',group:'error'};const hz=matchLibrary('hazardous',title),pre=matchLibrary('precursor',title),exp=matchLibrary('explosive',title);const all=[...hz,...pre,...exp],allNames=[...new Set(all.map(x=>x.raw||x.rule.name))];const generic=GENERIC_MARKERS.some(x=>title.includes(x)),mixture=MIXTURE_MARKERS.some(x=>title.includes(x)),conditional=hasConditional(all);let category,group,action;if(all.length){category=conditional?'类属／条件型风险候选':mixture?'混合物／副产品／废料风险候选':'具体化学品高风险候选';group='candidate';action='暂不放行；补充CAS号、SDS及适用条件后核验';}else if(generic||mixture){category=mixture?'混合物／副产品／废料，信息不足':'配方／功能型商品，信息不足';group='info';action='要求补充SDS、主要成分、含量、物态及必要的闪点';}else{category='当前纯规则未形成风险候选';group='clear';action='进入普通审核；不得仅凭未命中自动认定非毒危爆';}const toxic=pre.length?STATUS.candidate:STATUS.none;const hazard=(hz.length||exp.length)?STATUS.candidate:(generic||mixture?STATUS.info:STATUS.none);const explosive=exp.length?STATUS.candidate:STATUS.none;const parts=[];if(hz.length)parts.push(`危化候选：${names(hz).join('、')}`);if(pre.length)parts.push(`易制毒候选：${names(pre).join('、')}`);if(exp.length)parts.push(`易制爆候选：${names(exp).join('、')}；危化维度同步管控`);if(!all.length&&generic)parts.push('标题为配方或功能型产品，无法获得真实组分');if(!all.length&&mixture)parts.push('标题涉及混合物、副产品、废料或残液，无法确认实际组分及含量');if(!parts.length)parts.push('当前名称词典未召回，不等于确认不属于毒危爆');return {id,title,category,toxic,hazard,explosive,candidates:allNames.join('、'),action,note:parts.join('；'),group};}
function validateHazard(lib){const rules=lib?.rules||[];if(rules.length!==2833||lib.verified!==true||lib.completeness!=='complete')return false;const nums=rules.map(r=>String(r.catalog_no||'')).filter(x=>/^\d+$/.test(x)).map(Number),set=new Set(nums);if(nums.length!==2828||set.size!==2828)return false;for(let i=1;i<=2828;i++)if(!set.has(i))return false;return rules.filter(r=>String(r.id||'').startsWith('HAZ-2026-ADD-')).length===5;}
async function loadRules(){try{const [h,p,e]=await Promise.all(['data/hazardous_catalog_2026.json','data/precursor_catalog_47.json','data/explosive_catalog_74.json'].map(u=>fetch(u,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`${u} HTTP ${r.status}`);return r.json()})));const libs={hazardous:h.library,precursor:p.library,explosive:e.library};if(!validateHazard(libs.hazardous))throw new Error('危化规则库未通过2,833条结构校验');if((libs.precursor.rules||[]).length!==47||libs.precursor.verified!==true)throw new Error('易制毒规则库未通过47项校验');if((libs.explosive.rules||[]).length!==74||libs.explosive.verified!==true)throw new Error('易制爆规则库未通过74项校验');state.libraries=libs;for(const k of Object.keys(libs))state.indexes[k]=buildIndex(libs[k]);setRuleCard('haz',libs.hazardous);setRuleCard('pre',libs.precursor);setRuleCard('exp',libs.explosive);$('loadNotice').className='notice success';$('loadNotice').innerHTML='<div>✓</div><div><strong>规则库已通过完整性校验</strong>已加载2,833条危化、47项易制毒和74项易制爆规则。可开始单条或批量标题筛查。</div>';$('singleBtn').disabled=false;if(state.rows.length)$('runBtn').disabled=false;}catch(err){console.error(err);$('loadNotice').className='notice warn';$('loadNotice').innerHTML=`<div>⚠</div><div><strong>规则库加载失败</strong>${esc(err.message)}。当前页面已锁定识别功能，避免使用不完整规则库。</div>`;}}
function setRuleCard(prefix,lib){$(prefix+'Count').textContent=lib.rules.length;$(prefix+'Version').textContent=`${lib.version||''} · 更新/生效 ${lib.effective_date||'-'}`;const pill=$(prefix+'Pill');pill.textContent='完整';pill.className='pill ok';}
function detectHeader(matrix){const canon=s=>normTerm(s);for(let i=0;i<Math.min(matrix.length,30);i++){const row=matrix[i]||[],map={};row.forEach((v,j)=>{const n=canon(v);for(const [k,als] of Object.entries(HEADER_ALIASES))if(als.some(a=>canon(a)===n))map[k]=j;});if(map.title!==undefined)return {row:i,map};}return null;}
function matrixToRows(matrix){const hit=detectHeader(matrix);if(!hit)throw new Error('未找到“商品标题/商品名称”列。请保留表头，或使用标准模板。');const out=[];for(let i=hit.row+1;i<matrix.length;i++){const r=matrix[i]||[],title=String(r[hit.map.title]??'').trim(),id=String(hit.map.id===undefined?i-hit.row:r[hit.map.id]??'').trim()||String(i-hit.row);if(title||r.some(v=>String(v??'').trim()))out.push({id,title});}return out;}
async function parseFile(file){const lower=file.name.toLowerCase();if(lower.endsWith('.csv')){const text=await file.text(),wb=XLSX.read(text,{type:'string'}),ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});}const buf=await file.arrayBuffer(),wb=XLSX.read(buf,{type:'array',cellDates:false}),ws=wb.Sheets[wb.SheetNames[0]];return XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});}
function updateKpis(){const r=state.results;$('kTotal').textContent=r.length;$('kCandidate').textContent=r.filter(x=>x.group==='candidate').length;$('kInfo').textContent=r.filter(x=>x.group==='info').length;$('kClear').textContent=r.filter(x=>x.group==='clear').length;$('kError').textContent=r.filter(x=>x.group==='error').length;}
function statusClass(value){if(value===STATUS.candidate)return 'block';if(value===STATUS.info)return 'review';if(value===STATUS.error)return 'error';return 'clear';}
function render(){updateKpis();const q=normTerm($('search').value),f=$('filter').value;let rows=state.results.filter(x=>(f==='all'||x.group===f)&&(!q||normTerm(`${x.id} ${x.title} ${x.candidates} ${x.category}`).includes(q)));const shown=rows.slice(0,500);$('shownMeta').textContent=rows.length>500?`${rows.length}条（页面显示前500条，导出包含全部）`:`${rows.length}条`;if(!shown.length){$('tbody').innerHTML='<tr><td colspan="9" class="empty">暂无符合条件的数据。</td></tr>';return;}$('tbody').innerHTML=shown.map(x=>`<tr><td>${esc(x.id)}</td><td>${esc(x.title)}</td><td>${esc(x.category)}</td><td><span class="status ${statusClass(x.toxic)}">${esc(x.toxic)}</span></td><td><span class="status ${statusClass(x.hazard)}">${esc(x.hazard)}</span></td><td><span class="status ${statusClass(x.explosive)}">${esc(x.explosive)}</span></td><td class="candidate">${esc(x.candidates||'-')}</td><td>${esc(x.action)}</td><td>${esc(x.note)}</td></tr>`).join('');}
async function runBatch(){if(state.running||!state.rows.length||!state.libraries.hazardous)return;state.running=true;$('runBtn').disabled=true;state.results=[];const total=state.rows.length,chunk=200;try{for(let i=0;i<total;i+=chunk){const end=Math.min(total,i+chunk);for(let j=i;j<end;j++)state.results.push(analyze(state.rows[j]));$('progress').style.width=`${(end/total)*100}%`;$('progressText').textContent=`正在识别 ${end.toLocaleString()}/${total.toLocaleString()}…`;if(i%1000===0)render();await new Promise(r=>setTimeout(r,0));}render();$('progressText').textContent=`识别完成：${total.toLocaleString()}条。页面最多展示500条，导出包含全部结果。`;$('exportXlsx').disabled=false;$('exportCsv').disabled=false;}catch(err){$('progressText').textContent=`识别失败：${err.message}`;console.error(err);}finally{state.running=false;$('runBtn').disabled=false;}}
function exportRows(){return state.results.map(x=>({'编号':x.id,'商品标题':x.title,'纯规则处理类别':x.category,'毒（易制毒）判断':x.toxic,'危（危险化学品）判断':x.hazard,'爆（易制爆）判断':x.explosive,'标题候选':x.candidates,'建议处置':x.action,'备注':x.note}));}
function exportXlsx(){const data=exportRows(),ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();ws['!cols']=[{wch:16},{wch:48},{wch:30},{wch:24},{wch:26},{wch:24},{wch:34},{wch:42},{wch:80}];XLSX.utils.book_append_sheet(wb,ws,'判断明细');const summary=XLSX.utils.aoa_to_sheet([['指标','数量'],['总数据',state.results.length],['标题风险候选',state.results.filter(x=>x.group==='candidate').length],['信息不足',state.results.filter(x=>x.group==='info').length],['未形成候选',state.results.filter(x=>x.group==='clear').length],['数据错误',state.results.filter(x=>x.group==='error').length],[],['口径','标题命中仅作为风险候选；未命中不等于确认非毒危爆。']]);XLSX.utils.book_append_sheet(wb,summary,'结果摘要');XLSX.writeFile(wb,`毒危爆标题纯规则识别结果_${new Date().toISOString().slice(0,10)}.xlsx`,{compression:true});}
function csvCell(v){const s=String(v??'');return /[",\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s;}
function exportCsv(){const data=exportRows(),heads=Object.keys(data[0]||{'编号':''}),lines=[heads,...data.map(o=>heads.map(h=>o[h]))].map(r=>r.map(csvCell).join(','));const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`毒危爆标题纯规则识别结果_${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function single(){const title=$('singleTitle').value.trim();if(!title){$('singleResult').innerHTML='<div class="result-box muted">请输入商品标题。</div>';return;}const r=analyze({id:'SINGLE',title});$('singleResult').innerHTML=`<div class="result-box"><strong>${esc(r.category)}</strong><div class="meta">${esc(r.action)}</div><div class="result-grid"><div class="dimension"><h4>毒（易制毒）</h4><span class="status ${statusClass(r.toxic)}">${esc(r.toxic)}</span></div><div class="dimension"><h4>危（危险化学品）</h4><span class="status ${statusClass(r.hazard)}">${esc(r.hazard)}</span></div><div class="dimension"><h4>爆（易制爆）</h4><span class="status ${statusClass(r.explosive)}">${esc(r.explosive)}</span></div></div><div style="margin-top:10px"><strong>标题候选：</strong>${esc(r.candidates||'无')}<br><strong>备注：</strong>${esc(r.note)}</div></div>`;}
$('fileInput').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(typeof XLSX==='undefined')throw new Error('Excel解析组件未加载，请刷新页面后重试');const matrix=await parseFile(file),rows=matrixToRows(matrix);state.rows=rows;state.results=[];$('fileMeta').textContent=`${file.name} · ${rows.length.toLocaleString()}条`;$('progress').style.width='0';$('progressText').textContent=`已导入${rows.length.toLocaleString()}条，等待执行识别。`;$('runBtn').disabled=!state.libraries.hazardous||!rows.length;$('exportXlsx').disabled=true;$('exportCsv').disabled=true;render();}catch(err){$('progressText').textContent=`导入失败：${err.message}`;}finally{e.target.value='';}});
$('runBtn').addEventListener('click',runBatch);$('clearBtn').addEventListener('click',()=>{state.rows=[];state.results=[];$('runBtn').disabled=true;$('exportXlsx').disabled=true;$('exportCsv').disabled=true;$('fileMeta').textContent='支持 .xlsx、.xlsm、.xls、.csv；建议包含“编号/样本ID”和“商品标题/商品名称”列';$('progress').style.width='0';$('progressText').textContent='尚未导入文件';render();});$('search').addEventListener('input',render);$('filter').addEventListener('change',render);$('exportXlsx').addEventListener('click',exportXlsx);$('exportCsv').addEventListener('click',exportCsv);$('singleBtn').addEventListener('click',single);$('singleTitle').addEventListener('keydown',e=>{if(e.key==='Enter')single();});
loadRules();
